services:
  web:
    build: .
#    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    command: [ "gunicorn", "django_project.wsgi", "-b", "0.0.0.0:8000" ]
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-es9&j60^r#n&#t%&4-dz*i!duiwv^chef#u!erd5hy#k+(s#nd"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: